//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_F83345.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;

    public partial class Image
    {
        public int ImageID { get; set; }
        public string ImgName { get; set; }
        [DisplayName("Upload Image")]
        public string ImgPath { get; set; }
        public string EmailID { get; set; }

        public IEnumerable<HttpPostedFileBase> ImageFile { get; set; }
    }
}
